name: validate CBTW challenge
run-name: testing solution submitted by ${{ github.actor }}
on: [push]
jobs:
  try-validation:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up
        uses: action/setup-python@v4
      - name: program produces a valid solution
        run: pytest -v



